import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { Cairo } from "next/font/google";
import Footer from "@/components/Footer";

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "عنوانك الأمثل لبيع وشراء المنتجات الرقمية الجاهزة - إسم الموقع",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="ar">
      <body
        className={` ${cairo.className} antialiased flex flex-col min-h-screen  `}
      >
        <Header />
        <div className="grid flex-1">
          <main className="w-screen mx-auto ">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
