export const productData = {
  id: "1",
  name: "Premium Wireless Headphones",
  description:
    "Experience crystal-clear sound with our premium wireless headphones. Features active noise cancellation, 40-hour battery life, and premium comfort for extended listening sessions.",
  price: 299.99,
  originalPrice: 399.99,
  discount: 25,
  rating: 4.8,
  reviews: 1250,
  images: [
    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
    "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&q=80",
  ],
  features: [
    "Active Noise Cancellation",
    "40-hour Battery Life",
    "Premium Build Quality",
    "Bluetooth 5.0",
    "Touch Controls",
    "Voice Assistant Support",
  ],
  specifications: {
    "Driver Size": "40mm",
    "Frequency Response": "20Hz - 20kHz",
    Impedance: "32 Ohm",
    "Battery Capacity": "800mAh",
    "Charging Time": "2 hours",
    Weight: "250g",
  },
  stock: 45,
  seller: {
    name: "AudioTech Pro",
    rating: 4.9,
    products: 128,
  },
};

export const products = [
  {
    id: "1",
    title: "دليل شامل للمنتجات الرقمية",
    author: "هاني للمنتجات الرقمية",
    price: 12,
    image: "/images/digital-products-guide.jpg",
    likes: 0,
    category: "كتب إلكترونية",
    rating: 4.5,
  },
  {
    id: "2",
    title: "كتاب دليل التسجيل والربح من موقع خمس..",
    author: "محمود الجزار",
    price: 4,
    originalPrice: 5,
    image: "/images/khamsat-guide.jpg",
    likes: 1,
    category: "كتب إلكترونية",
    rating: 4.0,
  },
  {
    id: "3",
    title: "الموسوعة الشاملة في التجارة الإلكترونية",
    author: "ياسين ثابت",
    price: 10,
    image: "/images/ecommerce-encyclopedia.jpg",
    likes: 1,
    category: "كتب إلكترونية",
    rating: 4.8,
  },
  {
    id: "4",
    title: "الدخل السلبي",
    author: "طارق السلو",
    price: 9.99,
    originalPrice: 19.99,
    image: "/images/passive-income.jpg",
    likes: 1,
    category: "كتب إلكترونية",
    rating: 4.2,
  },
  {
    id: "5",
    title: "كيف تربح الاموال من خلال ثلث برامج فقط",
    author: "reem Mohammad",
    price: 10,
    image: "/images/three-programs.jpg",
    likes: 1,
    category: "كتب إلكترونية",
    rating: 4.6,
  },

  {
    id: "6",
    title: "كيف تربح الاموال من خلال ثلث برامج فقط",
    author: "reem Mohammad",
    price: 10,
    image: "/images/three-programs.jpg",
    likes: 1,
    category: "كتب إلكترونية",
    rating: 4.6,
  },

  {
    id: "7",
    title: "كيف تربح الاموال من خلال ثلث برامج فقط",
    author: "reem Mohammad",
    price: 10,
    image: "/images/three-programs.jpg",
    likes: 1,
    category: "كتب إلكترونية",
    rating: 4.6,
  },

  {
    id: "8",
    title: "كيف تربح الاموال من خلال ثلث برامج فقط",
    author: "reem Mohammad",
    price: 10,
    image: "/images/three-programs.jpg",
    likes: 1,
    category: "كتب إلكترونية",
    rating: 4.6,
  },
];
